name: veersa_health
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  url_launcher: ^6.3.2
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  iconsax: ^0.0.8
  http: ^1.5.0
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  google_sign_in: ^6.3.0
  image_picker: ^1.2.0
  cloud_firestore: ^6.0.3
  flutter_dotenv: ^6.0.0
  smooth_page_indicator: ^1.2.1
  flutter_native_splash: ^2.4.7
  fl_chart: ^1.1.1
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4
  dio: ^5.9.0
  firebase_messaging: ^16.1.0
  geolocator: ^14.0.2
  firebase_core: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/avatars/
    - assets/images/onboarding/
    - assets/images/signup/
    - assets/images/booking/
    - assets/images/map/
    - assets/images/doctors_speciality/
    - assets/images/forget_password/
    - assets/logo/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500 
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" 
  min_sdk_android: 21